version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      maven:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      gradle:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      docker-compose:
        patterns:
          - "*"
