name: ci

on: [ push ]

jobs:

  Build_mvn:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - run: mvn clean compile test

  Build_gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update Gradle wrapper

      - run: ./gradlew clean assemble test jar --stacktrace
