name: ci

on: [ push ]

jobs:

  Build mvn:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    steps:

      - uses: actions/checkout@v4

      - run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE test;' -uroot -proot

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - run: mvn clean compile test

  Build gradle:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    steps:

      - uses: actions/checkout@v4

      - run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE test;' -uroot -proot

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - run: ./gradlew clean compile test
